modLoader="javafml"
loaderVersion="[43,)"
license="Unlicense"
[[mods]]
modId="plushed"
version="${file.jarVersion}"
displayName="Plushed"
displayURL="https://modrinth.com/project/plushed"
logoFile="icon.png"
credits="Made by EssieFir"
authors="Originally Made by Hibi, ported to Forge by agnor99"

description='''
Stop it! You're making me plush. (Plushie Mod)
'''
[[dependencies.plushed]]
    modId="forge"
    mandatory=true
    versionRange="[43.1.2,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.plushed]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
